
<table class="firstColFixed">
	<tr>
		<td><?php tr_e('Domain name') ?></td>
		<td>{VL_DOMAIN_NAME}</td>
	</tr>
	<tr>
		<td><?php tr_e('IP address') ?></td>
		<td>{VL_DOMAIN_IP}</td>
	</tr>
	<tr>
		<td><?php tr_e('Status') ?></td>
		<td>{VL_STATUS}</td>
	</tr>
	<tr>
		<td><?php tr_e('PHP') ?></td>
		<td>{VL_PHP_SUPP}</td>
	</tr>
	<tr>
		<td><?php tr_e('PHP Editor') ?></td>
		<td>{VL_PHP_EDITOR_SUPP}</td>
	</tr>
	<tr>
		<td><?php tr_e('CGI') ?></td>
		<td>{VL_CGI_SUPP}</td>
	</tr>
	<tr>
		<td><?php tr_e('DNS') ?></td>
		<td>{VL_DNS_SUPP}</td>
	</tr>
	<tr>
		<td><?php tr_e('External mail server') ?></td>
		<td>{VL_EXT_MAIL_SUPP}</td>
	</tr>
	<tr>
		<td><?php tr_e('Software installer') ?></td>
		<td>{VL_SOFTWARE_SUPP}</td>
	</tr>
	<tr>
		<td><?php tr_e('Backup') ?></td>
		<td>{VL_BACKUP_SUP}</td>
	</tr>
	<tr>
		<td><?php tr_e('Monthly traffic') ?></td>
		<td>
			<div class="graph"><span style="width:{VL_TRAFFIC_PERCENT}%">&nbsp;</span></div>
			{VL_TRAFFIC_USED} / {VL_TRAFFIC_LIMIT}
		</td>
	</tr>
	<tr>
		<td><?php tr_e('Diskspace') ?></td>
		<td>
			<div class="graph"><span style="width:{VL_DISK_PERCENT}%">&nbsp;</span></div>
			{VL_DISK_USED} / {VL_DISK_LIMIT}
		</td>
	</tr>
</table>

<table class="firstColFixed">
	<thead>
	<tr>
		<th><?php tr_e('Feature') ?></th>
		<th><?php tr_e('USed') ?>}</th>
		<th><?php tr_e('Limit') ?></th>
	</tr>
	</thead>
	<tbody>
	<tr>
		<td><?php tr_e('Subdomains') ?></td>
		<td>{VL_SUBDOM_ACCOUNTS_USED}</td>
		<td>{VL_SUBDOM_ACCOUNTS_LIMIT}</td>
	</tr>
	<tr>
		<td><?php tr_e('Domain aliases') ?></td>
		<td>{VL_DOMALIAS_ACCOUNTS_USED}</td>
		<td>{VL_DOMALIAS_ACCOUNTS_LIMIT}</td>
	</tr>
	<tr>
		<td><?php tr_e('Mail users') ?></td>
		<td>{VL_MAIL_ACCOUNTS_USED}</td>
		<td>{VL_MAIL_ACCOUNTS_LIMIT}</td>
	</tr>
	<tr>
		<td><?php tr_e('Mail quota') ?></td>
		<td>{VL_MAIL_QUOTA_USED}</td>
		<td>{VL_MAIL_QUOTA_LIMIT}</td>
	</tr>
	<tr>
		<td><?php tr_e('Ftp users') ?></td>
		<td>{VL_FTP_ACCOUNTS_USED}</td>
		<td>{VL_FTP_ACCOUNTS_LIMIT}</td>
	</tr>
	<tr>
		<td><?php tr_e('Sql databases') ?></td>
		<td>{VL_SQL_DB_ACCOUNTS_USED}</td>
		<td>{VL_SQL_DB_ACCOUNTS_LIMIT}</td>
	</tr>
	<tr>
		<td><?php tr_e('Sql users') ?></td>
		<td>{VL_SQL_USER_ACCOUNTS_USED}</td>
		<td>{VL_SQL_USER_ACCOUNTS_LIMIT}</td>
	</tr>
	</tbody>
</table>

<div class="buttons">
	<!-- BDP: edit_option -->
	<a class="link_as_button" href="domain_edit.php?edit_id={DOMAIN_ID}"><?php tr_e('Edit') ?></a>
	<!-- EDP: edit_option -->
	<a class="link_as_button" href="users.php"><?php tr_e('Back') ?></a>
</div>
