
<form name="personalChangeFrm" action="personal_change.php" method="post">
	<table class="firstColFixed">
		<thead>
		<tr>
			<th colspan="2"><?php tr_e('Personal data') ?></th>
		</tr>
		</thead>
		<tbody>
		<tr>
			<td><label for="fname"><?php tr_e('Firstname') ?></label></td>
			<td><input type="text" name="fname" id="fname" value="{FIRST_NAME}"/></td>
		</tr>
		<tr>
			<td><label for="lname"><?php tr_e('Lastname') ?></label></td>
			<td><input type="text" name="lname" id="lname" value="{LAST_NAME}"/></td>
		</tr>
		<tr>
			<td><label for="gender"><?php tr_e('Gender') ?></label></td>
			<td>
				<select id="gender" name="gender">
					<option value="M" {VL_MALE}><?php tr_e('Male') ?></option>
					<option value="F" {VL_FEMALE}><?php tr_e('Female') ?></option>
					<option value="U" {VL_UNKNOWN}><?php tr_e('Unknown') ?></option>
				</select>
			</td>
		</tr>
		<tr>
			<td><label for="firm"><?php tr_e('Compagny') ?></label></td>
			<td><input type="text" name="firm" id="firm" value="{FIRM}"/></td>
		</tr>
		<tr>
			<td><label for="street1"><?php tr_e('Street 1') ?></label></td>
			<td><input type="text" name="street1" id="street1" value="{STREET_1}"/></td>
		</tr>
		<tr>
			<td><label for="street2"><?php tr_e('Street 2') ?></label></td>
			<td><input type="text" name="street2" id="street2" value="{STREET_2}"/></td>
		</tr>
		<tr>
			<td><label for="zip"><?php tr_e('Zip') ?></label></td>
			<td><input type="text" name="zip" id="zip" value="{ZIP}"/></td>
		</tr>
		<tr>
			<td><label for="city"><?php tr_e('City') ?></label></td>
			<td><input type="text" name="city" id="city" value="{CITY}"/></td>
		</tr>
		<tr>
			<td><label for="state"><?php tr_e('State') ?></label></td>
			<td><input type="text" name="state" id="state" value="{STATE}"/></td>
		</tr>
		<tr>
			<td><label for="country"><?php tr_e('Country') ?></label></td>
			<td><input type="text" name="country" id="country" value="{COUNTRY}"/></td>
		</tr>
		<tr>
			<td><label for="email"><?php tr_e('Email') ?></label></td>
			<td><input type="text" name="email" id="email" value="{EMAIL}"/></td>
		</tr>
		<tr>
			<td><label for="phone"><?php tr_e('Phone') ?></label></td>
			<td><input type="text" name="phone" id="phone" value="{PHONE}"/></td>
		</tr>
		<tr>
			<td><label for="fax"><?php tr_e('Fax') ?></label></td>
			<td><input type="text" name="fax" id="fax" value="{FAX}"/></td>
		</tr>
		</tbody>
	</table>

	<div class="buttons">
		<input name="Submit" type="submit" value="<?php tr_e('Update') ?>"/>
		<input type="hidden" name="uaction" value="updt_data"/>
	</div>
</form>
