
<script>
	function action_delete(subject) {
		if (subject == '#__all__#') {
			return confirm(html_entity_decode("{TR_TICKETS_DELETE_ALL_MESSAGE}"));
		} else {
			return confirm(sprintf(html_entity_decode("{TR_TICKETS_DELETE_MESSAGE}"), subject));
		}
	}
</script>

<!-- BDP: tickets_list -->
<table>
	<thead>
	<tr>
		<th><?php tr_e('Status') ?></th>
		<th><?php tr_e('From') ?></th>
		<th><?php tr_e('Subject') ?></th>
		<th><?php tr_e('Priority') ?></th>
		<th><?php tr_e('Last answer date') ?></th>
		<th><?php tr_e('Actions') ?></th>
	</tr>
	</thead>
	<tbody>
	<!-- BDP: tickets_item -->
	<tr>
		<td><strong>{TICKET_STATUS_VAL}</strong></td>
		<td>{TICKET_FROM_VAL}</td>
		<td>
			<a href="ticket_view.php?ticket_id={TICKET_ID_VAL}" class="icon i_document"
			   title="{TR_TICKET_READ_LINK}">{TICKET_SUBJECT_VAL}</a>
		</td>
		<td>{TICKET_URGENCY_VAL}</td>
		<td>{TICKET_LAST_DATE_VAL}</td>
		<td>
			<a href="ticket_delete.php?ticket_id={TICKET_ID_VAL}" class="icon i_delete"
			   onclick="return action_delete({TICKET_SUBJECT2_VAL}')"
			   title="{TR_TICKET_DELETE_LINK}">{TR_TICKET_DELETE}</a>

			<a href="ticket_closed.php?ticket_id={TICKET_ID_VAL}" class="icon i_open"
			   title="{TR_TICKET_REOPEN_LINK}">{TR_TICKET_REOPEN}</a>
		</td>
	</tr>
	<!-- EDP: tickets_item -->
	<tr>
		<td colspan="6">
			<div class="buttons">
				<a class="link_as_button" href="'ticket_delete.php?delete=closed"
				   onclick="return action_delete('#__all__#')">{TR_TICKET_DELETE_ALL}</a>
			</div>
		</td>
	</tr>
	</tbody>
</table>

<div class="paginator">
	<!-- BDP: scroll_prev -->
	<a class="icon i_prev" href="ticket_system.php?psi={PREV_PSI}" title="<?php tr_e('Previous') ?>"><?php tr_e('Previous') ?></a>
	<!-- EDP: scroll_prev -->
	<!-- BDP: scroll_prev_gray -->
	<span class="icon i_prev_gray"></span>
	<!-- EDP: scroll_prev_gray -->
	<!-- BDP: scroll_next_gray -->
	<span class="icon i_next_gray"></span>
	<!-- EDP: scroll_next_gray -->
	<!-- BDP: scroll_next -->
	<a class="icon i_next" href="ticket_system.php?psi={NEXT_PSI}" title="<?php tr_e('Next') ?>"><?php tr_e('Next') ?></a>
	<!-- EDP: scroll_next -->
</div>
<!-- EDP: tickets_list -->
