
<script>
	$(document).ready(function () {
		<!-- BDP: php_editor_js -->
		// PHP Editor settings dialog
		$('#php_editor_dialog').dialog({
			hide: 'blind',
			show: 'slide',
			focus: false,
			autoOpen: false,
			width: 650,
			modal: true,
			buttons:{ '{TR_CLOSE}': function(){ $(this).dialog('close'); } }
		});

		$(window).scroll(function() {
			$("#php_editor_dialog").dialog("option", "position", { my: "center", at: "center", of: window });
		});

		$('#addFrm2').submit(function (){ $('#php_editor_dialog').parent().appendTo($(this)); });

		if ($('#php_no').is(':checked')){ $('#php_editor_block').hide(); }

		$('#php_yes,#php_no').change(function (){
			$('#php_editor_block').toggle();
		});

		var php_editor_dialog_open = $('#php_editor_dialog_open');

		php_editor_dialog_open.button({ icons:{ primary: "ui-icon-gear" } }).click(function (e) {
			$('#php_editor_dialog').dialog('open');
		});

		if ($('#phpiniSystemNo').is(':checked')){ php_editor_dialog_open.hide(); }

		$('#phpiniSystemYes,#phpiniSystemNo').change(function (){ php_editor_dialog_open.fadeToggle(); });

		var phpDirectivesResellerMaxValues = {PHP_DIRECTIVES_RESELLER_MAX_VALUES};
		var errorMessages = $('.php_editor_error');

		function _updateErrorMesssages(k, t) {
			if (t != undefined) {
				if (!$('#err_' + k).length) {
					$("#msg_default").remove();
					errorMessages.append('<span style="display:block" id="err_' + k + '">' + t + '</span>').
						removeClass('success').addClass('error');
				}
			} else if ($('#err_' + k).length) {
				$('#err_' + k).remove();
			}

			if ($.trim(errorMessages.text()) == '') {
				errorMessages.empty().append('<span id="msg_default"><?php tr_e('All parameter values are valid') ?></span>').
					removeClass('error').addClass('success');
			}
		}

		$.each(phpDirectivesResellerMaxValues, function (k, v) {
			$('#' + k).keyup(function () {
				var r = /^(0|[1-9]\d*)$/; // Regexp to check value syntax
				var nv = $(this).val(); // Get new value to be checked

				if (!r.test(nv) || parseInt(nv) > parseInt(v)) {
					$(this).addClass('ui-state-error');
					_updateErrorMesssages(k, sprintf('{TR_VALUE_ERROR}', k, 0, v));
				} else {
					$(this).removeClass('ui-state-error');
					_updateErrorMesssages(k);
				}
			}).trigger('keyup');
		});
		<!-- EDP: php_editor_js -->
	});
</script>

<!-- BDP: add_user -->
<form id="addFrm2" name="addFrm2" method="post" action="user_add2.php">
<table class="firstColFixed">
	<thead>
	<tr>
		<th colspan="2"><?php tr_e('Hosting plan') ?></th>
	</tr>
	</thead>
	<tbody>
	<tr>
		<td><?php tr_e('Name') ?></td>
		<td><input name="template" type="hidden" id="template" value="{VL_TEMPLATE_NAME}"/>{VL_TEMPLATE_NAME}</td>
	</tr>
	</tbody>
</table>

<table class="firstColFixed">
	<thead>
	<tr>
		<th colspan="2"><?php tr_e('Limits') ?></th>
	</tr>
	</thead>
	<tbody>
	<!-- BDP: subdomain_feature -->
	<tr>
		<td><label for="nreseller_max_subdomain_cnt"><?php tr_e('Max subdomains') ?></label></td>
		<td><input id="nreseller_max_subdomain_cnt" type="text" name="nreseller_max_subdomain_cnt"
				   value="{MAX_SUBDMN_CNT}"/></td>
	</tr>
	<!-- EDP: subdomain_feature -->
	<!-- BDP: alias_feature -->
	<tr>
		<td><label for="nreseller_max_alias_cnt"><?php tr_e('Max domain aliases') ?></label></td>
		<td><input id="nreseller_max_alias_cnt" type="text" name="nreseller_max_alias_cnt" value="{MAX_DMN_ALIAS_CNT}"/>
		</td>
	</tr>
	<!-- EDP: alias_feature -->
	<!-- BDP: mail_feature -->
	<tr>
		<td><label for="nreseller_max_mail_cnt"><?php tr_e('Max mail users') ?></label></td>
		<td><input id="nreseller_max_mail_cnt" type="text" name="nreseller_max_mail_cnt" value="{MAX_MAIL_CNT}"/></td>
	</tr>
	<tr>
		<td><label for="nreseller_mail_quota"><?php tr_e('Mail quota') ?></label></td>
		<td><input id="nreseller_mail_quota" type="text" name="nreseller_mail_quota" value="{MAIL_QUOTA}"/></td>
	</tr>
	<!-- EDP: mail_feature -->
	<!-- BDP: ftp_feature -->
	<tr>
		<td><label for="nreseller_max_ftp_cnt"><?php tr_e('Max ftp users') ?></label></td>
		<td><input id="nreseller_max_ftp_cnt" type="text" name="nreseller_max_ftp_cnt" value="{MAX_FTP_CNT}"/></td>
	</tr>
	<!-- EDP: ftp_feature -->
	<!-- BDP: sql_feature -->
	<tr>
		<td><label for="nreseller_max_sql_db_cnt"><?php tr_e('Max sql databases') ?></label></td>
		<td><input id="nreseller_max_sql_db_cnt" type="text" name="nreseller_max_sql_db_cnt" value="{MAX_SQL_CNT}"/>
		</td>
	</tr>
	<tr>
		<td><label for="nreseller_max_sql_user_cnt"><?php tr_e('Max sql users') ?></label></td>
		<td>
			<input id="nreseller_max_sql_user_cnt" type="text" name="nreseller_max_sql_user_cnt"
				   value="{VL_MAX_SQL_USERS}"/>
		</td>
	</tr>
	<!-- EDP: sql_feature -->
	<tr>
		<td><label for="nreseller_max_traffic"><?php tr_e('Monthly traffic limit') ?></label></td>
		<td><input id="nreseller_max_traffic" type="text" name="nreseller_max_traffic" value="{VL_MAX_TRAFFIC}"/></td>
	</tr>
	<tr>
		<td><label for="nreseller_max_disk"><?php tr_e('Max diskspace') ?></label></td>
		<td><input id="nreseller_max_disk" type="text" name="nreseller_max_disk" value="{VL_MAX_DISK_USAGE}"/></td>
	</tr>
	</tbody>
</table>

<table class="firstColFixed">
<thead>
<tr>
	<th colspan="2"><?php tr_e('Features') ?></th>
</tr>
</thead>
<tbody>
<tr>
	<td><?php tr_e('PHP') ?></td>
	<td>
		<div class="radio">
			<input type="radio" id="php_yes" name="php" value="_yes_" {VL_PHPY} />
			<label for="php_yes"><?php tr_e('Yes') ?></label>
			<input type="radio" id="php_no" name="php" value="_no_" {VL_PHPN} />
			<label for="php_no"><?php tr_e('No') ?></label>
		</div>
	</td>
</tr>
<!-- BDP: php_editor_block -->
<tr id="php_editor_block">
	<td><label><?php tr_e('PHP Editor') ?></label></td>
	<td colspan="2">
		<div class="radio">
			<input type="radio" name="phpiniSystem" id="phpiniSystemYes" value="yes" {PHP_EDITOR_YES}/>
			<label for="phpiniSystemYes"><?php tr_e('Yes') ?></label>
			<input type="radio" name="phpiniSystem" id="phpiniSystemNo" value="no" {PHP_EDITOR_NO}/>
			<label for="phpiniSystemNo"><?php tr_e('No') ?></label>
			<button type="button" name="php_editor_dialog_open" id="php_editor_dialog_open"><?php tr_e('Settings') ?></button>
		</div>
		<div style="margin:0" id="php_editor_dialog" title="{TR_PHP_EDITOR_SETTINGS}">
			<div class="php_editor_error success">
				<span id="msg_default"><?php tr_e('All parameter values are valid.') ?></span>
			</div>
			<!-- BDP: php_editor_permissions_block -->
			<table class="firstColFixed">
				<thead>
				<tr>
					<th colspan="2"><?php tr_e('Permissions') ?></th>
				</tr>
				</thead>
				<tbody>
				<!-- BDP: php_editor_allow_url_fopen_block -->
				<tr>
					<td>{TR_CAN_EDIT_ALLOW_URL_FOPEN}</td>
					<td>
						<div class="radio">
							<input type="radio" name="phpini_perm_allow_url_fopen" id="phpiniAllowUrlFopenYes"
								   value="yes" {ALLOW_URL_FOPEN_YES}/>
							<label for="phpiniAllowUrlFopenYes"><?php tr_e('Yes') ?></label>
							<input type="radio" name="phpini_perm_allow_url_fopen" id="phpiniAllowUrlFopenNo"
								   value="no" {ALLOW_URL_FOPEN_NO}/>
							<label for="phpiniAllowUrlFopenNo"><?php tr_e('No') ?></label>
						</div>
					</td>
				</tr>
				<!-- EDP: php_editor_allow_url_fopen_block -->
				<!-- BDP: php_editor_display_errors_block -->
				<tr>
					<td>{TR_CAN_EDIT_DISPLAY_ERRORS}</td>
					<td>
						<div class="radio">
							<input type="radio" name="phpini_perm_display_errors" id="phpiniDisplayErrorsYes"
								   value="yes" {DISPLAY_ERRORS_YES}/>
							<label for="phpiniDisplayErrorsYes"><?php tr_e('Yes') ?></label>
							<input type="radio" name="phpini_perm_display_errors" id="phpiniDisplayErrorsNo"
								   value="no" {DISPLAY_ERRORS_NO}/>
							<label for="phpiniDisplayErrorsNo"><?php tr_e('No') ?></label>
						</div>
					</td>
				</tr>
				<!-- EDP: php_editor_display_errors_block -->
				<!-- BDP: php_editor_disable_functions_block -->
				<tr>
					<td>{TR_CAN_EDIT_DISABLE_FUNCTIONS}</td>
					<td>
						<div class="radio">
							<input type="radio" name="phpini_perm_disable_functions" id="phpiniDisableFunctionsYes"
								   value="yes" {DISABLE_FUNCTIONS_YES}/>
							<label for="phpiniDisableFunctionsYes"><?php tr_e('Yes') ?></label>
							<input type="radio" name="phpini_perm_disable_functions" id="phpiniDisableFunctionsNo"
								   value="no" {DISABLE_FUNCTIONS_NO}/>
							<label for="phpiniDisableFunctionsNo"><?php tr_e('No') ?></label>
							<input type="radio" name="phpini_perm_disable_functions" id="phpiniDisableFunctionsExec"
								   value="exec" {DISABLE_FUNCTIONS_EXEC}/>
							<label for="phpiniDisableFunctionsExec"><?php tr_e('Only exec') ?></label>
						</div>
					</td>
				</tr>
				<!-- EDP: php_editor_disable_functions_block -->
				</tbody>
			</table>
			<!-- EDP: php_editor_permissions_block -->
			<!-- BDP: php_editor_default_values_block -->
			<table class="firstColFixed">
				<thead>
				<tr>
					<th colspan="2">{TR_DIRECTIVES_VALUES}</th>
				</tr>
				</thead>
				<tbody>
				<tr>
					<td><label for="post_max_size">{TR_PHP_POST_MAX_SIZE_DIRECTIVE}</label></td>
					<td>
						<input name="post_max_size" id="post_max_size" type="text" value="{POST_MAX_SIZE}"/>
						<span><?php tr_e('MiB') ?></span>
					</td>
				</tr>
				<tr>
					<td><label for="upload_max_filezize">{PHP_UPLOAD_MAX_FILEZISE_DIRECTIVE}</label></td>
					<td>
						<input name="upload_max_filezize" id="upload_max_filezize" type="text"
							   value="{UPLOAD_MAX_FILESIZE}"/> <span><?php tr_e('MiB') ?></span>
					</td>
				</tr>
				<tr>
					<td><label for="max_execution_time">{TR_PHP_MAX_EXECUTION_TIME_DIRECTIVE}</label></td>
					<td>
						<input name="max_execution_time" id="max_execution_time" type="text"
							   value="{MAX_EXECUTION_TIME}"/> <span><?php tr_e('Seconds') ?></span>
					</td>
				</tr>
				<tr>
					<td><label for="max_input_time">{TR_PHP_MAX_INPUT_TIME_DIRECTIVE}</label></td>
					<td>
						<input name="max_input_time" id="max_input_time" type="text" value="{MAX_INPUT_TIME}"/>
						<span><?php tr_e('Seconds') ?></span>
					</td>
				</tr>
				<tr>
					<td><label for="memory_limit">{TR_PHP_MEMORY_LIMIT_DIRECTIVE}</label></td>
					<td>
						<input name="memory_limit" id="memory_limit" type="text" value="{MEMORY_LIMIT}"/>
						<span><?php tr_e('MiB') ?></span>
					</td>
				</tr>
				</tbody>
			</table>
			<!-- EDP: php_editor_default_values_block -->
		</div>
	</td>
</tr>
<!-- EDP: php_editor_block -->
<tr>
	<td>{TR_CGI}</td>
	<td>
		<div class="radio">
			<input type="radio" id="cgi_yes" name="cgi" value="_yes_" {VL_CGIY} />
			<label for="cgi_yes"><?php tr_e('Yes') ?></label>
			<input type="radio" id="cgi_no" name="cgi" value="_no_" {VL_CGIN} />
			<label for="cgi_no"><?php tr_e('No') ?></label>
		</div>
	</td>
</tr>
<!-- BDP: custom_dns_records_feature -->
<tr>
	<td><?php tr_e('DNS') ?></td>
	<td>
		<div class="radio">
			<input type="radio" id="dns_yes" name="dns" value="_yes_" {VL_DNSY} />
			<label for="dns_yes"><?php tr_e('Yes') ?></label>
			<input type="radio" id="dns_no" name="dns" value="_no_" {VL_DNSN} />
			<label for="dns_no"><?php tr_e('No') ?></label>
		</div>
	</td>
</tr>
<!-- EDP: custom_dns_records_feature -->
<!-- BDP: ext_mail_feature -->
<tr>
	<td><?php tr_e('External mail server') ?></td>
	<td>
		<div class="radio">
			<input type="radio" id="extmail_yes" name="external_mail" value="_yes_" {VL_EXTMAILY} />
			<label for="extmail_yes"><?php tr_e('Yes') ?></label>
			<input type="radio" id="extmail_no" name="external_mail" value="_no_" {VL_EXTMAILN} />
			<label for="extmail_no"><?php tr_e('No') ?></label>
		</div>
	</td>
</tr>
<!-- EDP: ext_mail_feature -->
<!-- BDP: aps_feature -->
<tr>
	<td><?php tr_e('Software installer') ?></td>
	<td>
		<div class="radio">
			<input type="radio" name="software_allowed" value="_yes_" {VL_SOFTWAREY} id="software_allowed_yes"/>
			<label for="software_allowed_yes"><?php tr_e('Yes') ?></label>
			<input type="radio" name="software_allowed" value="_no_" {VL_SOFTWAREN} id="software_allowed_no"/>
			<label for="software_allowed_no"><?php tr_e('No') ?></label>
		</div>
	</td>
</tr>
<!-- EDP: aps_feature -->
<!-- BDP: backup_feature -->
<tr>
	<td><?php tr_e('Backup') ?></td>
	<td>
		<div class="radio">
			<input type="radio" id="backup_dmn" name="backup" value="_dmn_" {VL_BACKUPD} />
			<label for="backup_dmn"><?php tr_e('Domain') ?></label>
			<input type="radio" id="backup_sql" name="backup" value="_sql_" {VL_BACKUPS} />
			<label for="backup_sql"><?php tr_e('Sql') ?></label>
			<input type="radio" id="backup_full" name="backup" value="_full_" {VL_BACKUPF} />
			<label for="backup_full"><?php tr_e('Full') ?></label>
			<input type="radio" id="backup_no" name="backup" value="_no_" {VL_BACKUPN} />
			<label for="backup_no"><?php tr_e('No') ?></label>
		</div>
	</td>
</tr>
<!-- EDP: backup_feature -->
<!-- BDP: web_folder_protection_feature -->
<tr>
	<td>
		<label for="web_folder_protection"><?php tr_e('Web folder protection') ?></label>
		<span style="vertical-align:middle" class="icon i_help" id="web_folder_protection_help"
			  title="{TR_WEB_FOLDER_PROTECTION_HELP}"></span>
	</td>
	<td>
		<div class="radio">
			<input type="radio" id="web_folder_protection_yes" name="web_folder_protection"
				   value="_yes_" {VL_WEB_FOLDER_PROTECTION_YES} />
			<label for="web_folder_protection_yes"><?php tr_e('Yes') ?></label>
			<input type="radio" id="web_folder_protection_no" name="web_folder_protection"
				   value="_no_" {VL_WEB_FOLDER_PROTECTION_NO} />
			<label for="web_folder_protection_no"><?php tr_e('No') ?></label>
		</div>
	</td>
</tr>
<!-- EDP: web_folder_protection_feature -->
</tbody>

</table>

<div class="buttons">
	<input type="hidden" name="uaction" value="user_add2_nxt"/>
	<input name="Submit" type="submit" value="<?php tr_e('Next step') ?>"/>
</div>
</form>
<!-- EDP: add_user -->
