
<form name="user_edit" method="post" action="user_edit.php?edit_id={EDIT_ID}" autocomplete="off">
	<table class="firstColFixed">
		<thead>
		<tr>
			<th colspan="2"><?php tr_e('Core data') ?></th>
		</tr>
		</thead>
		<tbody>
		<tr>
			<td><?php tr_e('Username') ?></td>
			<td>{VL_USERNAME}</td>
		</tr>
		<tr>
			<td><label for="userpassword"><?php tr_e('Password') ?></label></td>
			<td>
				<input type="password" name="userpassword" id="userpassword" value="{VAL_PASSWORD}" autocomplete="off"/>
				<input name="genpass" type="submit" value="{TR_PASSWORD_GENERATE}"/>
			</td>
		</tr>
		<tr>
			<td><label for="userpassword_repeat"><?php tr_e('Password confirmation') ?></label></td>
			<td>
				<input type="password" name="userpassword_repeat" id="userpassword_repeat" value="{VAL_PASSWORD}"
					   autocomplete="off"/>
			</td>
		</tr>
		<tr>
			<td><label for="useremail"><?php tr_e('Email') ?></label></td>
			<td><input type="text" name="useremail" id="useremail" value="{VL_MAIL}"/></td>
		</tr>
		</tbody>
	</table>

	<table class="firstColFixed">
		<thead>
		<tr>
			<th colspan="2"><?php tr_e('Personal data') ?></th>
		</tr>
		</thead>
		<tbody>
		<tr>
			<td><label for="useruid">{<?php tr_e('Customer ID') ?>}</label></td>
			<td><input type="text" name="useruid" id="useruid" value="{VL_USR_ID}"/></td>
		</tr>
		<tr>
			<td><label for="userfname"><?php tr_e('Firstname') ?></label></td>
			<td><input type="text" name="userfname" id="userfname" value="{VL_USR_NAME}"/></td>
		</tr>
		<tr>
			<td><label for="userlname"><?php tr_e('Lastname') ?></label></td>
			<td><input type="text" name="userlname" id="userlname" value="{VL_LAST_USRNAME}"/></td>
		</tr>
		<tr>
			<td><label for="gender"><?php tr_e('Gender') ?></label></td>
			<td>
				<select id="gender" name="gender">
					<option value="M"{VL_MALE}><?php tr_e('Male') ?></option>
					<option value="F"{VL_FEMALE}><?php tr_e('Female') ?></option>
					<option value="F"{VL_UNKNOWN}><?php tr_e('Unknown') ?></option>
				</select>
			</td>
		</tr>
		<tr>
			<td><label for="userfirm"><?php tr_e('Compagny') ?></label></td>
			<td><input type="text" name="userfirm" id="userfirm" value="{VL_USR_FIRM}"/></td>
		</tr>
		<tr>
			<td><label for="userstreet1"><?php tr_e('Street 1') ?></label></td>
			<td><input type="text" name="userstreet1" id="userstreet1" value="{VL_STREET1}"/></td>
		</tr>
		<tr>
			<td><label for="userstreet2"><?php tr_e('Street 2') ?></label></td>
			<td><input type="text" name="userstreet2" id="userstreet2" value="{VL_STREET2}"/></td>
		</tr>
		<tr>
			<td><label for="userzip"><?php tr_e('Zip') ?></label></td>
			<td><input type="text" name="userzip" id="userzip" value="{VL_USR_POSTCODE}"/></td>
		</tr>
		<tr>
			<td><label for="usercity"><?php tr_e('City') ?></label></td>
			<td><input type="text" name="usercity" id="usercity" value="{VL_USRCITY}"/></td>
		</tr>
		<tr>
			<td><label for="userstate"><?php tr_e('State') ?></label></td>
			<td><input id="userstate" type="text" name="userstate" value="{VL_USRSTATE}"/></td>
		</tr>
		<tr>
			<td><label for="usercountry"><?php tr_e('Country') ?></label></td>
			<td><input type="text" name="usercountry" id="usercountry" value="{VL_COUNTRY}"/></td>
		</tr>
		<tr>
			<td><label for="userphone"><?php tr_e('Phone') ?></label></td>
			<td><input type="text" name="userphone" id="userphone" value="{VL_PHONE}"/></td>
		</tr>
		<tr>
			<td><label for="userfax"><?php tr_e('Fax') ?></label></td>
			<td><input type="text" name="userfax" id="userfax" value="{VL_FAX}"/></td>
		</tr>
		</tbody>
	</table>

	<div class="buttons">
		<input name="submit" type="submit" value="<?php tr_e('Update') ?>"/>
		<input type="checkbox" id="send_data" name="send_data"/>
		<label for="send_data"><?php tr_e('Send data') ?></label>
		<input type="hidden" name="uaction" value="save_changes"/>
		<input type="hidden" name="edit_id" value="{EDIT_ID}"/>
	</div>
</form>
