
<script>
	$(document).ready(function () {
		$("input[name='url_forwarding']").change(
			function () {
				if ($("#url_forwarding_no").is(':checked')) {
					$("#tr_url_forwarding_data").hide();
				} else {
					$("#tr_url_forwarding_data").show();
				}
			}
		).trigger('change');
	});
</script>

<form name="edit_domain_alias_frm" method="post" action="alias_edit.php?id={DOMAIN_ALIAS_ID}">
	<table class="firstColFixed">
		<thead>
		<tr>
			<th colspan="2"><?php tr_e('Domain alias') ?>}</th>
		</tr>
		</thead>
		<tbody>
		<tr>
			<td><label for="domain_alias_name"><?php tr_e('Name') ?></label></td>
			<td>
				<span class="bold">www .</span>
				<input type="text" name="domain_alias_name" id="domain_alias_name" value="{DOMAIN_ALIAS_NAME}"
					   readonly="readonly"/>
			</td>
		</tr>
		<tr>
			<td><?php tr_e('URL forwarding') ?> <span class="tips icon i_help" title="{TR_URL_FORWARDING_TOOLTIP}"></span></td>
			<td>
				<div class="radio">
					<input type="radio" name="url_forwarding" id="url_forwarding_yes"{FORWARD_URL_YES} value="yes"/>
					<label for="url_forwarding_yes"><?php tr_e('Yes') ?></label>
					<input type="radio" name="url_forwarding" id="url_forwarding_no"{FORWARD_URL_NO} value="no"/>
					<label for="url_forwarding_no"><?php tr_e('No') ?></label>
				</div>
			</td>
		</tr>
		<tr id="tr_url_forwarding_data">
			<td><?php tr_e('Forward to URL') ?></td>
			<td>
				<label for="forward_url_scheme">
					<select name="forward_url_scheme" id="forward_url_scheme">
						<option value="http://"{HTTP_YES}>Http</option>
						<option value="https://"{HTTPS_YES}>Https</option>
						<option value="ftp://"{FTP_YES}>Ftp</option>
					</select>
				</label>
				<label>
					<input name="forward_url" type="text" id="forward_url" value="{FORWARD_URL}"/>
				</label>
			</td>
		</tr>
		</tbody>
	</table>

	<div class="buttons">
		<input name="Submit" type="submit" value="<?php tr_e('Update') ?>"/>
		<a class="link_as_button" href="domains_manage.php"><?php tr_e('Cancel') ?></a>
	</div>
</form>
