
<form name="cert_edit" method="post" action="cert_view.php?id={ID}&type={TYPE}">
	<table class="firstColFixed">
		<thead>
		<tr>
			<th colspan="2"><?php tr_e('SSL certificate') ?></th>
		</tr>
		</thead>
		<tbody>
		<tr>
			<td><?php tr_e('Common name') ?></td>
			<td>{DOMAIN_NAME}</td>
		</tr>
		<tr>
			<td><?php tr_e('Status') ?></td>
			<td>{STATUS}</td>
		</tr>
		<tr>
			<td><label for="pass"><?php tr_e('Passphrase') ?></label></td>
			<td><input id="pass" type="password" name="pass" value="" autocomplete="off"/></td>
		</tr>
		<tr>
			<td><label for="pass_rep"><?php tr_e('Passphrase confirmation') ?></label></td>
			<td><input id="pass_rep" type="password" name="pass_rep" value="" autocomplete="off"/></td>
		</tr>
		<tr>
			<td><label for="key_cert"><?php tr_e('Private key') ?></label></td>
			<td><textarea name="key_cert" id="key_cert">{KEY_CERT}</textarea></td>
		</tr>
		<tr>
			<td><label for="cert_cert"><?php tr_e('Certificate') ?></label></td>
			<td><textarea name="cert_cert" id="cert_cert">{CERT}</textarea></td>
		</tr>
		<tr>
			<td><label for="ca_cert"><?php tr_e('Intermediate certificate (CA bundle)') ?></label></td>
			<td><textarea name="ca_cert" id="ca_cert">{CA_CERT}</textarea></td>
		</tr>
		</tbody>
	</table>

	<div class="buttons">
		<!-- BDP: cert_enable -->
		<input name="send" type="submit" value="<?php tr_e('Save') ?>"/>
		<!-- EDP: cert_enable -->
		<input name="delete" type="submit" value="<?php tr_e('Delete') ?>"/>
		<a class="link_as_button" href="domains_manage.php"><?php tr_e('Cancel') ?></a>
	</div>
</form>
