#!/bin/sh

# i-MSCP - internet Multi Server Control Panel
# Copyright (C) 2010-2014 by i-MSCP - internet Multi Server Control Panel
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# The i-MSCP Home Page is:
#
#    http://i-mscp.net
#

# description:
#
# create/update the imscp.pot file

set -e

I18N=../

if [ ! -d ${I18N}/po ]; then
	echo "You must run this script from the i18n/tools directory."
	exit 1
fi

# Purge any old language file
rm -fR ${I18N}/po/*.po

GUI=../../gui

if [ ! -f ${GUI}/public/index.php ]; then
	echo "${GUI} isn't a valid GUI location."
	exit 1
fi

# PHP|PHTML files
/usr/bin/xgettext \
--language=PHP \
-d "i-MSCP" \
--copyright-holder="i-MSCP Team - All rights reserved" \
--package-name="i-MSCP" \
--package-version="1.1.6" \
--msgid-bugs-address="i18n@i-mscp.net" \
--keyword="tr_e" \
--keyword="tr" \
--from-code=utf-8 \
${GUI}/library/*.php \
${GUI}/library/iMSCP/*.php \
${GUI}/library/iMSCP/*/*.php \
${GUI}/library/iMSCP/*/*/*.php \
${GUI}/library/resources/i18n/zend.php \
${GUI}/library/iMSCP/View/Helpers/Functions/*.php \
${GUI}/public/*.php \
${GUI}/public/*/*.php \
${GUI}/themes/*/*.phtml \
${GUI}/themes/*/*/*.phtml \
${GUI}/themes/*/*/*/*.phtml \
${GUI}/themes/*/*/*/*/*.phtml \
--no-wrap \
-p ${I18N}/po \
-o ${I18N}/iMSCP.pot -s

# XML files
/usr/bin/xgettext \
--foreign-user \
--language=Glade \
-d "i-MSCP" \
--copyright-holder="i-MSCP Team - All rights reserved" \
--package-name="i-MSCP" \
--package-version="1.1.6" \
--msgid-bugs-address="i18n@i-mscp.net" \
--keyword="label" \
${GUI}/themes/*/*/*.xml \
--no-wrap \
-p ${I18N}/po \
-o ${I18N}/iMSCP.pot -j -s

exit 0
