
<script>
	$(document).ready(function () {
		$.ajaxSetup({
			url: $(location).attr('pathname'),
			type: 'GET',
			datatype: 'text',
			beforeSend: function (xhr) {
				xhr.setRequestHeader('Accept', 'text/plain');
			},
			success: function (r) {
				$('#password, #password_confirmation').val(r);
			},
			error: iMSCPajxError
		});

		$('#generate_password').click(function () {
			$.ajax();
		});

		$('#reset_password').click(function () {
			$('#password, #password_confirmation').val('');
		});

		// Create dialog box for some messages (password and notices)
		$('#dialog_box').dialog({
			modal: true,
			autoOpen: false,
			hide: 'blind',
			show: 'blind',
			buttons: { Ok: function () {
				$(this).dialog('close');
			}}
		});

		// Show generated password in specific dialog box
		$('#show_password').click(function () {
			var password = $('#password').val();

			if (password == '') {
				password = "<?php tr_e('You must first generate a password') ?>";
			} else {
				password = '<strong>' + $('#password').val() + '</strong>';
			}

			$('#dialog_box').dialog("option", "title", "<?php tr_e('Password') ?>").html(password);
			$('#dialog_box').dialog('open');
		});
	});
</script>

<div id="dialog_box"></div>

<form name="admin_add_user" method="post" action="admin_add.php">
	<!-- BDP: props_list -->
	<table class="firstColFixed">
		<thead>
		<tr>
			<th colspan="3"><?php tr_e('Core data') ?></th>
		</tr>
		</thead>
		<tbody>
		<tr>
			<td><label for="username"><?php tr_e('Username') ?></label></td>
			<td colspan="2">
				<input type="text" name="username" id="username" value="{USERNAME}"/>
			</td>
		</tr>
		<tr>
			<td><label for="password"><?php tr_e('Password') ?></label></td>
			<td style="width: 235px;">
				<input type="password" name="password" id="password" value="" autocomplete="off"/>
			</td>
			<td>
				<button type="button" id="generate_password"><?php tr_e('Generate') ?></button>
				<button type="button" id="show_password"><?php tr_e('Show') ?></button>
				<button type="button" id="reset_password"><?php tr_e('Reset') ?></button>
			</td>
		</tr>
		<tr>
			<td><label for="password_confirmation"><?php tr_e('Password confirmation') ?></label></td>
			<td colspan="2">
				<input type="password" name="password_confirmation" id="password_confirmation" value=""
					   autocomplete="off"/>
			</td>
		</tr>
		<tr>
			<td><label for="email"><?php tr_e('Email'); ?></label></td>
			<td colspan="2"><input type="text" name="email" id="email" value="{EMAIL}"/></td>
		</tr>
		</tbody>
	</table>
	<table class="firstColFixed">
		<thead>
		<tr>
			<th colspan="2"><?php tr_e('Personal data'); ?></th>
		</tr>
		</thead>
		<tbody>
		<tr>
			<td><label for="first_name"><?php tr_e('First name'); ?></label></td>
			<td><input type="text" name="fname" id="first_name" value="{FIRST_NAME}"/></td>
		</tr>
		<tr>
			<td><label for="last_name"><?php tr_e('Last name'); ?></label></td>
			<td><input type="text" name="lname" id="last_name" value="{LAST_NAME}"/></td>
		</tr>
		<tr>
			<td><label for="gender"><?php tr_e('Gender'); ?></label></td>
			<td>
				<select id="gender" name="gender">
					<option value="M" {VL_MALE}><?php tr_e('Male'); ?></option>
					<option value="F" {VL_FEMALE}><?php tr_e('Female'); ?></option>
					<option value="U" {VL_UNKNOWN}><?php tr_e('Unknown'); ?></option>
				</select>
			</td>
		</tr>
		<tr>
			<td><label for="firm"><?php tr_e('Compagny'); ?></label></td>
			<td><input type="text" name="firm" id="firm" value="{FIRM}"/></td>
		</tr>
		<tr>
			<td><label for="street1"><?php tr_e('Street 1'); ?></label></td>
			<td><input type="text" name="street1" id="street1" value="{STREET_1}"/></td>
		</tr>
		<tr>
			<td><label for="street2"><?php tr_e('Street 2'); ?></label></td>
			<td><input type="text" name="street2" id="street2" value="{STREET_2}"/></td>
		</tr>
		<tr>
			<td><label for="zip"><?php tr_e('Zip'); ?></label></td>
			<td><input type="text" name="zip" id="zip" value="{ZIP}"/></td>
		</tr>
		<tr>
			<td><label for="city"><?php tr_e('City'); ?></label></td>
			<td><input type="text" name="city" id="city" value="{CITY}"/></td>
		</tr>
		<tr>
			<td><label for="state"><?php tr_e('State'); ?></label></td>
			<td><input type="text" name="state" id="state" value="{STATE}"/></td>
		</tr>
		<tr>
			<td><label for="country"><?php tr_e('Country'); ?></label></td>
			<td><input type="text" name="country" id="country" value="{COUNTRY}"/></td>
		</tr>
		<tr>
			<td><label for="phone"><?php tr_e('Phone'); ?></label></td>
			<td><input type="text" name="phone" id="phone" value="{PHONE}"/></td>
		</tr>
		<tr>
			<td><label for="fax"><?php tr_e('Fax'); ?></label></td>
			<td><input type="text" name="fax" id="fax" value="{FAX}"/></td>
		</tr>
		</tbody>
	</table>
	<!-- EDP: props_list -->

	<div class="buttons">
		<input name="submit" type="submit" value="<?php tr_e('Create'); ?>"/>
		<input type="hidden" name="uaction" value="add_user"/>
	</div>
</form>
