
<form name="domain_statistics_frm" method="post" action="domain_statistics.php?domain_id={DOMAIN_ID}">
	<label for="month"><?php tr_e('Mois') ?></label>
	<select id="month" name="month">
		<!-- BDP: month_list -->
		<option {OPTION_SELECTED}>{MONTH_VALUE}</option>
		<!-- EDP: month_list -->
	</select>
	<label for="year"><?php tr_e('Year') ?></label>
	<select name="year" id="year">
		<!-- BDP: year_list -->
		<option value="{VALUE}" {OPTION_SELECTED}>{HUMAN_VALUE}</option>
		<!-- EDP: year_list -->
	</select>
	<input name="Submit" type="submit" value="<?php tr_e('Show') ?>"/>
	<input name="domain_id" type="hidden" value="{DOMAIN_ID}"/>
</form>

<!-- BDP: domain_statistics_block -->
<table>
	<thead>
	<tr>
		<th><?php tr_e('Day') ?></th>
		<th><?php tr_e('Web traffic') ?></th>
		<th><?php tr_e('Ftp traffic') ?></th>
		<th><?php tr_e('SMTP traffic') ?></th>
		<th><?php tr_e('POP3 traffic') ?></th>
		<th><?php tr_e('Total traffic') ?></th>
	</tr>
	</thead>
	<tfoot>
	<tr>
		<td><?php tr_e('Day') ?></td>
		<td><?php tr_e('Web traffic') ?></td>
		<td><?php tr_e('Ftp traffic') ?></td>
		<td><?php tr_e('SMTP traffic') ?></td>
		<td><?php tr_e('POP3 traffic') ?></td>
		<td><?php tr_e('Total traffic') ?></td>
	</tr>
	</tfoot>
	<tbody>
	<!-- BDP: traffic_table_item -->
	<tr>
		<td>{DATE}</td>
		<td>{WEB_TRAFFIC}</td>
		<td>{FTP_TRAFFIC}</td>
		<td>{SMTP_TRAFFIC}</td>
		<td>{POP3_TRAFFIC}</td>
		<td>{ALL_TRAFFIC}</td>
	</tr>
	<!-- EDP: traffic_table_item -->
	</tbody>
</table>
<!-- EDP: domain_statistics_block -->
