
<!-- BDP hosting_plans_js -->
<script>
	function action_delete(subject) {
		return confirm(sprintf(html_entity_decode("{TR_MESSAGE_DELETE}"), subject));
	}
</script>
<!-- EDP hosting_plans_js -->

<!-- BDP: hosting_plans -->
<table class="firstColFixed">
	<thead>
	<tr>
		<th><?php tr_e('No') ?>}</th>
		<th><?php tr_e('Name') ?></th>
		<th><?php tr_e('Status') ?></th>
		<th><?php tr_e('Actions') ?></th>
	</tr>
	</thead>
	<tbody>
	<!-- BDP: hosting_plan -->
	<tr>
		<td>{NUMBER}</td>
		<td>{NAME}</td>
		<td>{STATUS}</td>
		<td>
			<a href="hosting_plan_edit.php?id={ID}" class="icon i_edit"><?php tr_e('Edit') ?></a>
			<a href="hosting_plan_delete.php?id={ID}" onclick="return action_delete('{NAME}')"
			   class="icon i_delete"><?php tr_e('Delete') ?></a>
		</td>
	</tr>
	<!-- EDP: hosting_plan -->
	</tbody>
</table>
<!-- EDP: hosting_plans -->
