
<table class="firstColFixed">
	<thead>
	<tr>
		<th><?php tr_e('Properties') ?></th>
		<th>{TR_VALUES}</th>
	</tr>
	</thead>
	<tbody>
	<tr>
		<td><?php tr_e('Administrators') ?></td>
		<td>{ADMIN_USERS}</td>
	</tr>
	<tr>
		<td><?php tr_e('Resellers') ?></td>
		<td>{RESELLER_USERS}</td>
	</tr>
	<tr>
		<td><?php tr_e('Customers') ?></td>
		<td>{NORMAL_USERS}</td>
	</tr>
	<tr>
		<td><?php tr_e('Domains') ?>}</td>
		<td>{DOMAINS}</td>
	</tr>
	<tr>
		<td><?php tr_e('Subdomains') ?></td>
		<td>{SUBDOMAINS}</td>
	</tr>
	<tr>
		<td><?php tr_e('Domain aliases') ?></td>
		<td>{DOMAINS_ALIASES}</td>
	</tr>
	<tr>
		<td><?php tr_e('Mail users') ?>}</td>
		<td>{MAIL_ACCOUNTS}</td>
	</tr>
	<tr>
		<td><?php tr_e('Ftp users') ?></td>
		<td>{FTP_ACCOUNTS}</td>
	</tr>
	<tr>
		<td><?php tr_e('Databases') ?></td>
		<td>{SQL_DATABASES}</td>
	</tr>
	<tr>
		<td><?php tr_e('SQL users') ?></td>
		<td>{SQL_USERS}</td>
	</tr>
	</tbody>
</table>

<h2 class="traffic"><span><?php tr_e('Server traffic') ?></span></h2>

<p>{TRAFFIC_WARNING}</p>

<div class="graph">
	<span style="width:{TRAFFIC_PERCENT}%">&nbsp;</span>
</div>
