
<script>
	$(document).ready(function () {
		errFieldsStack = {ERR_FIELDS_STACK};
		$.each(errFieldsStack, function () {
			$("#" + this).css('border-color', '#ca1d11');
		});
		$('.datatable').dataTable(
				{
					"oLanguage": <?php echo getDataTablesPluginTranslations() ?>,
					"bStateSave": true
				}
		);

		$('table a').replaceWith(function () {
			var href = $(this).attr('href');
			if (href == "#") {
				return '<span class="icon i_error">' + $(this).text() + "</span>";
			}
			return '<a class="icon i_delete" href="' + href + '" onclick="' + $(this).attr('onclick') + '">' + $(this).text() + "</a>";
		});
	});

	// Delete the given ip address
	function confirm_deletion(ip_address) {
		return confirm(sprintf(html_entity_decode("{TR_MESSAGE_DELETE}"), ip_address));
	}
</script>

<p class="hint" style="font-variant: small-caps;font-size: small;">{TR_TIP}</p>
<br />

<!-- BDP: ip_addresses_block -->
<h3 class="ip"><span><?php tr_e('Configured IP addresses') ?></span></h3>
<table class="datatable">
	<thead>
	<tr>
		<th><?php tr_e('IP address') ?></th>
		<th><?php tr_e('Network card') ?></th>
		<th><?php tr_e('Actions') ?></th>
	</tr>
	</thead>
	<tbody>
	<!-- BDP: ip_address_block -->
	<tr>
		<td>{IP}</td>
		<td>{NETWORK_CARD}</td>
		<td>
			<a class="icon i_delete" href="{ACTION_URL}" onclick="return confirm_deletion('{IP}')" title="{ACTION_NAME}"
			   class="{STATUS}">{ACTION_NAME}</a>
		</td>
	</tr>
	<!-- EDP: ip_address_block -->
	</tbody>
</table>
<!-- EDP: ip_addresses_block -->

<!-- BDP: ip_address_form_block -->
<h3 class="ip"><span><?php tr_e('New IP address') ?></span></h3>

<form name="addIpFrm" method="post" action="ip_manage.php">
	<table class="firstColFixed">
		<thead>
		<tr>
			<th colspan="2"><?php tr_e('IP address data') ?></th>
		</tr>
		</thead>
		<tbody>
		<tr>
			<td><label for="ip_number"><?php tr_e('IP address') ?></label></td>
			<td><input name="ip_number" id="ip_number" type="text" value="{VALUE_IP}" maxlength="39"/></td>
		</tr>
		<tr>
			<td><label for="ip_card"><?php tr_e('Network card') ?></label></td>
			<td>
				<select name="ip_card" id="ip_card">
					<!-- BDP: network_card_block -->
					<option {SELECTED}>{NETWORK_CARD}</option>
					<!-- EDP: network_card_block -->
				</select>
			</td>
		</tr>
		</tbody>
	</table>
	<div class="buttons">
		<button name="submit" type="submit"><?php tr_e('Add') ?></button>
		<a class="link_as_button" href="settings.php"><?php tr_e('Cancel') ?></a>
	</div>
</form>
<!-- EDP: ip_address_form_block -->
