
<script>
	function action_status(dmn_name) {
		return confirm(sprintf(html_entity_decode("{TR_MESSAGE_CHANGE_STATUS}"), dmn_name));
	}

	function action_delete(dmn_name) {
		return  confirm(sprintf(html_entity_decode("{TR_MESSAGE_DELETE}"), dmn_name));
	}
</script>

<h3 class="user_yellow"><span><?php tr_e('Administrators') ?></span></h3>

<!-- BDP: admin_message -->
<div class="info">{ADMIN_MESSAGE}</div>
<!-- EDP: admin_message -->

<!-- BDP: admin_list -->
<table class="firstColFixed">
	<thead>
	<tr>
		<th><?php tr_e('Username') ?></th>
		<th><?php tr_e('Created on') ?></th>
		<th><?php tr_e('Created by') ?></th>
		<th><?php tr_e('Actions') ?></th>
	</tr>
	</thead>
	<tbody>
	<!-- BDP: admin_item -->
	<tr>
		<td>{ADMIN_USERNAME}</td>
		<td>{ADMIN_CREATED_ON}</td>
		<td>{ADMIN_CREATED_BY}</td>
		<td>
			<a href="{URL_EDIT_ADMIN}" class="icon i_user" title="{TR_EDIT}"><?php tr_e('Edit') ?></a>

			<!-- BDP: admin_delete_show -->
			<!-- EDP: admin_delete_show -->

			<!-- BDP: admin_delete_link -->
			<a href="{URL_DELETE_ADMIN}" class="icon i_delete" onclick="return action_delete('{ADMIN_USERNAME}')"
			   class="link" title="{TR_DELETE}"><?php tr_e('Delete') ?></a>
			<!-- EDP: admin_delete_link -->
		</td>
	</tr>
	<!-- EDP: admin_item -->
	</tbody>
</table>
<!-- EDP: admin_list -->

<h3 class="user_green"><span><?php tr_e('Resellers') ?></span></h3>

<!-- BDP: rsl_message -->
<div class="info">{RSL_MESSAGE}</div>
<!-- EDP: rsl_message -->

<!-- BDP: rsl_list -->
<table class="firstColFixed">
	<thead>
	<tr>
		<th><?php tr_e('Username') ?></th>
		<th><?php tr_e('Created on') ?></th>
		<th><?php tr_e('Created by') ?></th>
		<th><?php tr_e('Actions') ?></th>
	</tr>
	</thead>
	<tbody>
	<!-- BDP: rsl_item -->
	<tr>
		<td>{RSL_USERNAME}</td>
		<td>{RESELLER_CREATED_ON}</td>
		<td>{RSL_CREATED_BY}</td>
		<td>
			<a class="icon i_details" href="{URL_CHANGE_INTERFACE}"
			   title="<?php tr_e('Change user interface') ?>">{GO_TO_USER_INTERFACE}</a>
			<a href="{URL_EDIT_RSL}" class="icon i_user" title="<?php tr_e('Edit') ?>"><?php tr_e('Edit') ?></a>
			<a href="{URL_DELETE_RSL}" class="icon i_delete" title="<?php tr_e('Delete') ?>"
			   onclick="return action_delete('{RSL_USERNAME}')"><?php tr_e('Delete') ?></a>
		</td>
	</tr>
	<!-- EDP: rsl_item -->
	</tbody>
</table>
<!-- EDP: rsl_list -->

<h3 class="user_blue"><span><?php tr_e('Customers') ?></span></h3>

<!-- BDP: search_form -->
<form action="manage_users.php" method="post" name="search_user" id="search_user">
	<div style="line-height:40px;vertical-align: middle; float: left">
		<label><input name="search_for" type="text" value="{SEARCH_FOR}"/></label>
		<label>
		<select name="search_common">
			<option value="domain_name" {M_DOMAIN_NAME_SELECTED}>{M_DOMAIN_NAME}</option>
			<option value="customer_id" {M_CUSTOMER_ID_SELECTED}>{M_CUSTOMER_ID}</option>
			<option value="lname" {M_LAST_NAME_SELECTED}>{M_LAST_NAME}</option>
			<option value="firm" {M_COMPANY_SELECTED}>{M_COMPANY}</option>
			<option value="city" {M_CITY_SELECTED}>{M_CITY}</option>
			<option value="state" {M_STATE_SELECTED}>{M_STATE}</option>
			<option value="country" {M_COUNTRY_SELECTED}>{M_COUNTRY}</option>
		</select>
		</label>
		<label>
		<select name="search_status">
			<option value="all" {M_ALL_SELECTED}>{M_ALL}</option>
			<option value="ok" {M_OK_SELECTED}>{M_OK}</option>
			<option value="disabled" {M_SUSPENDED_SELECTED}>{M_SUSPENDED}</option>
		</select>
		</label>
		<input type="hidden" name="uaction" value="go_search"/>
		<input type="hidden" name="details" value=""/>
		<input name="Submit" type="submit" value="{TR_SEARCH}"/>
	</div>
	<div style="line-height:40px;vertical-align: middle; float: right">
		<a class="icon i_show_alias" href="#" title="<?php tr_e('Show details') ?>"
		   onclick="return sbmt_details(document.forms[0],'{SHOW_DETAILS}');"><?php tr_e('Show details') ?></a>
	</div>
	<div style="clear:both"></div>
</form>
<!-- EDP: search_form -->

<!-- BDP: usr_message -->
<div class="info">{USR_MESSAGE}</div>
<!-- EDP: usr_message -->

<!-- BDP: usr_list -->
<table>
	<thead>
	<tr>
		<th><?php tr_e('Status') ?></th>
		<th><?php tr_e('Username') ?></th>
		<th><?php tr_e('Created on') ?></th>
		<th><?php tr_e('Created by') ?></th>
		<th><?php tr_e('Actions') ?></th>
	</tr>
	</thead>
	<tbody>
	<!-- BDP: usr_item -->
	<tr>
		<td>
			<a href="{URL_CHANGE_STATUS}" onclick="return action_status('{USR_USERNAME}')"
			   class="icon i_{STATUS}" title="<?php tr_e('Status') ?>"><?php tr_e('Status') ?></a>
		</td>
		<td>
			<!-- BDP: usr_status_reload_true -->
			<a href="http://{USR_USERNAME}/" target="_blank" class="icon i_goto">{USR_USERNAME}</a>
			<!-- EDP: usr_status_reload_true -->
			<!-- BDP: usr_status_reload_false -->
			<span class="icon i_goto">{USR_USERNAME}</span>
			<!-- EDP: usr_status_reload_false -->
		</td>
		<td>{USER_CREATED_ON}</td>
		<td>{USR_CREATED_BY}</td>
		<td>
			<a class="icon i_identity" href="domain_details.php?domain_id={DOMAIN_ID}" title="<?php tr_e('Details') ?>"><?php tr_e('Details') ?></a>
			<a class="icon i_details" href="{URL_CHANGE_INTERFACE}"
			   title="{TR_CHANGE_USER_INTERFACE}">{GO_TO_USER_INTERFACE}</a>
			<!-- BDP: edit_option -->
			<a class="icon i_edit" href="domain_edit.php?edit_id={DOMAIN_ID}" title="<?php tr_e('Edit domain') ?>"><?php tr_e('Edit domain') ?></a>
			<!-- EDP: edit_option -->
			<a class="icon i_user" href="{URL_EDIT_USR}" title="<?php tr_e('Edit customer') ?>"><?php tr_e('Edit customer') ?></a>
			<!-- BDP: usr_delete_show -->
			<!-- EDP: usr_delete_show -->
			<!-- BDP: usr_delete_link -->
			<a class="icon i_delete" href="user_delete.php?user_id={USER_ID}" title="<?php tr_e('Delete') ?>"><?php tr_e('Delete') ?></a>
			<!-- EDP: usr_delete_link -->
		</td>
	</tr>
	<!-- BDP: user_details -->
	<tr>
		<td colspan="5"><a href="http://www.{ALIAS_DOMAIN}/" target="_blank" class="icon i_goto">{ALIAS_DOMAIN}</a></td>
	</tr>
	<!-- EDP: user_details -->
	<!-- EDP: usr_item -->
	</tbody>
</table>

<div class="paginator">
	<!-- BDP: scroll_prev -->
	<a class="icon i_prev" href="manage_users.php?psi={PREV_PSI}" title="<?php tr_e('Previous') ?>"><?php tr_e('Previous') ?></a>
	<!-- EDP: scroll_prev -->
	<!-- BDP: scroll_prev_gray -->
	<span class="icon i_prev_gray"></span>
	<!-- EDP: scroll_prev_gray -->
	<!-- BDP: scroll_next_gray -->
	<span class="icon i_next_gray"></span>
	<!-- EDP: scroll_next_gray -->
	<!-- BDP: scroll_next -->
	<a class="icon i_next" href="manage_users.php?psi={NEXT_PSI}" title="<?php tr_e('Next') ?>"><?php tr_e('Next') ?></a>
	<!-- EDP: scroll_next -->
</div>
<!-- EDP: usr_list -->
