
<table class="firstColFixed">
	<thead>
	<tr>
		<th><?php tr_e('Username') ?></th>
		<th><?php tr_e('Login on') ?></th>
		<th><?php tr_e('Actions') ?></th>
	</tr>
	</thead>
	<tbody>
	<!-- BDP: user_session -->
	<tr>
		<td>{ADMIN_USERNAME}</td>
		<td>{LOGIN_TIME}</td>
		<td>
			<a href="{DISCONNECT_LINK}" class="icon i_delete">{<?php tr_e('Force logout') ?></a>
			<a href="{KILL_LINK}" class="icon i_delete"><?php tr_e('Kill session') ?></a>
		</td>
	</tr>
	<!-- EDP: user_session -->
	</tbody>
</table>
