#!/bin/sh

umask 027

export PHPRC={PHP_STARTER_DIR}/{DOMAIN_NAME}/php5/
export PHP_FCGI_MAX_REQUESTS={PHP_FCGI_MAX_REQUESTS}
export TMPDIR={WEB_DIR}/data/tmp

SOCKET=/var/run/imscp_panel.sock
PIDFILE=/var/run/imscp_panel.pid

CHILDREN={PHP_FCGI_CHILDREN}
USER={SYSTEM_USER_PREFIX}{SYSTEM_USER_MIN_UID}
GROUP={SYSTEM_USER_PREFIX}{SYSTEM_USER_MIN_UID}

{SPAWN_FCGI_BIN} -s $SOCKET -M 0660 -P $PIDFILE -C $CHILDREN -u $USER -g $GROUP -- {PHP_CGI_BIN} "$@"

